# Atividade 07 - Módulo 04 - Q-Learning

* Aluno: João Luiz Grave Gross
* Data: 21/11/2020

In [1]:
import random
from random import randint
import pandas as pd
import numpy as np

In [2]:
# mostra a posição
def printTable(p):
  table = pd.DataFrame(np.zeros((4,4),dtype=int),columns=None)
  table.iloc[3,3]='X'
  table.iloc[3,1]='T'
  table.iloc[0,3]='T'
  T = pd.DataFrame({'linhas':[0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3],'colunas':[0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3]})
  table = table.replace(0,'_')
  table.iloc[T['linhas'][p],T['colunas'][p]] = 'o'
  print(table.to_string(index=False,header=False))
  print('')

In [3]:
printTable(np.random.randint(0,16))

 _  _  _  T
 _  _  _  _
 _  _  _  _
 o  T  _  X

| 0 4  8 12| \
| 1 5  9 13| \
| 2 6 10 14| \
| 3 7 11 15|

In [4]:
R = np.array([[-1,  0, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
              [ 0, -1,  0, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
              [-1,  0, -1,  0, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
              [-1, -1,  0, -1, -1, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1],
              [ 0, -1, -1, -1, -1,  0, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1],
              [-1,  0, -1, -1,  0, -1,  0, -1, -1,  0, -1, -1, -1, -1, -1, -1],
              [-1, -1,  0, -1, -1,  0, -1,  0, -1, -1,  0, -1, -1, -1, -1, -1],
              [-1, -1, -1,  0, -1, -1,  0, -1, -1, -1, -1,  0, -1, -1, -1, -1],
              [-1, -1, -1, -1,  0, -1, -1, -1, -1,  0, -1, -1,  0, -1, -1, -1],
              [-1, -1, -1, -1, -1,  0, -1, -1,  0, -1,  0, -1, -1,  0, -1, -1],
              [-1, -1, -1, -1, -1, -1,  0, -1, -1,  0, -1,  0, -1, -1,  0, -1],
              [-1, -1, -1, -1, -1, -1, -1,  0, -1, -1,  0, -1, -1, -1, -1, 20],
              [-1, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1, -1, -1,  0, -1, -1],
              [-1, -1, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1,  0, -1,  0, -1],
              [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1,  0, -1, 20],
              [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 50]])
Rtable = pd.DataFrame(data=R)
Rtable

    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
0   -1   0  -1  -1   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
1    0  -1   0  -1   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
2   -1   0  -1   0  -1   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
3   -1  -1   0  -1  -1  -1  -1   0  -1  -1  -1  -1  -1  -1  -1  -1
4    0  -1  -1  -1  -1   0  -1  -1   0  -1  -1  -1  -1  -1  -1  -1
5   -1   0  -1  -1   0  -1   0  -1  -1   0  -1  -1  -1  -1  -1  -1
6   -1  -1   0  -1  -1   0  -1   0  -1  -1   0  -1  -1  -1  -1  -1
7   -1  -1  -1   0  -1  -1   0  -1  -1  -1  -1   0  -1  -1  -1  -1
8   -1  -1  -1  -1   0  -1  -1  -1  -1   0  -1  -1   0  -1  -1  -1
9   -1  -1  -1  -1  -1   0  -1  -1   0  -1   0  -1  -1   0  -1  -1
10  -1  -1  -1  -1  -1  -1   0  -1  -1   0  -1   0  -1  -1   0  -1
11  -1  -1  -1  -1  -1  -1  -1   0  -1  -1   0  -1  -1  -1  -1  20
12  -1  -1  -1  -1  -1  -1  -1  -1   0  -1  -1  -1  -1   0  -1  -1
13  -1  -1  -1  -1  -1  -1  -1  -1  -1   0  -1  -1   0  -1   0  -1
14  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   0  -1  -1   0  -1  20
15  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  50

In [5]:
# fator de exploração
gamma = 1.
# taxa de aprendizado
alpha = 0.5
# zera a matriz Q
Q = np.zeros((16,16))

In [6]:
# aprendendo
def agentLearn(episodes):
    for i in range(episodes):
        s = randint(0,15)
        path = [s]
        while True:
            a = randint(0,15)
            if R[s,a]>=0:
                if a==7 or a==12:
                    print("It's a trap!")
                    path.append(a)
                    printTable(a)
                    break
                else:
                    Q[s,a] = (1.-alpha)*Q[s,a] + alpha*(R[s,a] + gamma*max(Q[a,]))
                    s = a
                    path.append(s)
                    printTable(s)
                    if s==15:
                        print("EXIT!")
                        printTable(s)
                        break
        print('Path:',path)

In [7]:
agentLearn(1)

 _  _  _  T
 _  _  _  _
 _  o  _  _
 _  T  _  X

 _  _  _  T
 _  o  _  _
 _  _  _  _
 _  T  _  X

 _  _  _  T
 _  _  _  _
 _  o  _  _
 _  T  _  X

It's a trap!
 _  _  _  T
 _  _  _  _
 _  _  _  _
 _  o  _  X

Path: [5, 6, 5, 6, 7]

In [8]:
# verifica como a "memória" está indo
Qtable = pd.DataFrame(data=Q, dtype=int)
Qtable

    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
1    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
2    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
3    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
4    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
5    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
6    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
7    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
8    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
9    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
10   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
11   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
12   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
13   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
14   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
15   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

In [9]:
# aprendendo
def agentLearnFast(episodes):
    for i in range(episodes):
        s = randint(0,15)
        while True:
            a = randint(0,15)
            if R[s,a]>=0:
                if a==7 or a==12:
                    break
                else:
                    Q[s,a] = (1.-alpha)*Q[s,a] + alpha*(R[s,a] + gamma*max(Q[a,]))
                    s = a
                    if s==15:
                        break
    return Q

In [10]:
# zera a matriz Q
Q = np.zeros((16,16))

In [11]:
# aprendendo
Q = agentLearnFast(100)
# verifica como a "memória" está indo
Qtable = pd.DataFrame(data=Q,dtype=int)
Qtable

     0    1    2    3    4    5    6   ...   9    10   11  12   13   14   15
0     0  126    0    0  139    0    0  ...    0    0    0   0    0    0    0
1   130    0  138    0  137    0    0  ...    0    0    0   0    0    0    0
2     0  126    0  110    0  141    0  ...    0    0    0   0    0    0    0
3     0    0  131    0    0    0    0  ...    0    0    0   0    0    0    0
4   129    0    0    0    0  150    0  ...    0    0    0   0    0    0    0
5     0  119    0    0  131    0  159  ...  156    0    0   0    0    0    0
6     0    0   98    0    0  124    0  ...    0  164    0   0    0    0    0
7     0    0    0  101    0    0    0  ...    0    0  126   0    0    0    0
8     0    0    0    0  133    0    0  ...  160    0    0   0    0    0    0
9     0    0    0    0    0  145    0  ...    0  160    0   0  143    0    0
10    0    0    0    0    0    0  136  ...  139    0  166   0    0  157    0
11    0    0    0    0    0    0    0  ...    0  111    0   0    0    0  168
12    0    0    0    0    0    0    0  ...    0    0    0   0    7    0    0
13    0    0    0    0    0    0    0  ...  140    0    0   0    0  155    0
14    0    0    0    0    0    0    0  ...    0  122    0   0  109    0  187
15    0    0    0    0    0    0    0  ...    0    0    0   0    0    0  175

[16 rows x 16 columns]

In [12]:
# saindo do labirinto
def agentExit(Q):
  n = 0
  nmax = 30
  s = randint(0,15)
  while True:
    ns = random.choice(list(filter(lambda kv: kv[1] == max(Q[s,]), enumerate(Q[s,]))))[0]
    if R[s,ns]>=0:
        s = ns
        n +=1
        print(s)
        if s == 7 or s == 12:
            print("It's a trap!")
            break
        elif s == 15: 
            print("EXIT!")
            break
        if n == nmax: 
            print("LOST!")
            break
  print('Total steps:',n)

In [13]:
agentExit(Q)

15
EXIT!
Total steps: 1